routes/web.php
<?php

/**********************************ADMIN*************************************/


use Carbon\Carbon;

Route::namespace('Admin')->prefix('admin')->group(function (){
   $this->get('/panel','PanelController@index');
   $this->post('/panel/upload_image' , 'panelController@uploadImageSubject')->name('upload');
   $this->resource('/articles','ArticleController');
   $this->resource('/courses','CourseController');
   $this->resource('/episodes','EpisodeController');

});


//Route::resource('article');
/**********************************ADMIN*************************************/

app/Episode.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Episode extends Model
{
    protected $guarded = [];

    public function course(){
        return $this->belongsTo(Course::class);
    }

    public function path(){
        return "/courses/{$this->course->slug}/episode/{$this->number}";
    }
}

app/Http/Controllers/Admin/EpisodeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Episode;
use App\Http\Requests\EpisodeRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EpisodeController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $episodes = Episode::latest()->paginate(20);
        return view('Admin.Episodes.index',compact('episodes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.Episodes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EpisodeRequest $request)
    {
        auth()->loginUsingId(1);
        $episode = Episode::create($request->all());
        $this->setCourseTime($episode);
        return redirect(route('episodes.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Episode $episode
     * @return \Illuminate\Http\Response
     */
    public function edit(Episode $episode)
    {
        auth()->loginUsingId(1);
        return view('Admin.Episodes.edit',compact('episode'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param EpisodeRequest $request
     * @param Episode $episode
     * @return void
     */
    public function update(EpisodeRequest $request, Episode $episode)
    {
        $episode->update($request->all());
        $this->setCourseTime($episode);
        return redirect(route('episodes.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Episode $episode
     * @return void
     * @throws \Exception
     */
    public function destroy(Episode $episode)
    {
        $episode->delete();
        return redirect(route('episodes.index'));
    }
}

resources/views/Admin/Episodes/create.blade.php
@extends('Admin.master')

@section('content')

    <div class="panel panel-headline">
        <div class="panel-heading">
            <h3 class="panel-title">ایجاد ویدئو</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <!-- BORDERED TABLE -->
                    <div class="panel">

                        <div class="panel-body">
                            <form action="{{ route('episodes.store') }}" method="post" enctype="multipart/form-data">
                                {{csrf_field()}}
                                @include('Admin.error')
                                <div class="form-group col-md-12">
                                    <label for="title">عنوان ویدئو</label>
                                    <input type="text" class="form-control" placeholder="عنوان ویدئو" name="title" id="title" value="{{old('title')}}">
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-sm-6">
                                        <label for="course_id">دوره ی مربوطه</label>
                                        <select class="form-control" name="course_id" id="course_id">
                                            @foreach(\App\Course::latest()->get() as $course)

                                                <option value="{{ $course->id }}">{{ $course->title }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="title">وضعیت ویدئو</label>
                                        <select id="type" name="type" class="form-control">
                                            <option value="vip">اعضای ویژه</option>
                                            <option value="free" selected>رایگان</option>
                                            <option value="cach">نقدی</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="description">متن</label>
                                    <textarea rows="5" class="form-control" placeholder="متن" name="description" id="description">{{old('description')}}</textarea>
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-sm-6">
                                        <label for="videoUrl">لینک ویدئو</label>
                                        <input class="form-control" placeholder="لینک ویدئو" name="videoUrl" id="videoUrl" value="{{old('videoUrl')}}">
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="number">شماره ویدئو</label>
                                        <input class="form-control" placeholder="شماره ویدئو" name="number" id="number" value="{{old('number')}}">
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-sm-6">
                                        <label for="tags">برچسب ها</label>
                                        <input type="text" class="form-control" placeholder="برچسب ها" name="tags" id="tags" value="{{old('tags')}}">
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="time">زمان ویدئو</label>
                                        <input type="text" class="form-control" placeholder="زمان" name="time" id="time" value="{{old('time')}}">
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                   <input type="submit" value="ارسال ویدئو" class="btn btn-success">
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- END BORDERED TABLE -->
                </div>
            </div>
        </div>
    </div>


@endsection

@section('footer')
    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        window.onload = function() {
            CKEDITOR.replace( 'description', {
                filebrowserUploadUrl: '{{ route('upload',['_token' => csrf_token() ]) }}'
            });
        };
        $(document).ready(function(){
            $('#course_id').selectpicker({
                noneSelectedText : 'لطفا دوره ی مورد نظر را انتخاب کنید'
            });
        });
    </script>
@endsection

resources/views/Admin/Episodes/edit.blade.php
@extends('Admin.master')

@section('content')

    <div class="panel panel-headline">
        <div class="panel-heading">
            <h3 class="panel-title">ویرایش ویدئو</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel">

                        <div class="panel-body">
                            <form action="{{ route('episodes.update' , [ 'id' => $episode->id ])}}" method="post" enctype="multipart/form-data">
                              {{csrf_field()}}
                              {{method_field('PATCH')}}
                              @include('Admin.error')
                                <div class="form-group col-md-12">
                                    <label for="title">عنوان ویدئو</label>
                                    <input type="text" class="form-control" placeholder="عنوان ویدئو" name="title" id="title" value="{{$episode->title}}">
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-sm-6">
                                        <label for="course_id">دوره ی مربوطه</label>
                                        <select class="form-control" name="course_id" id="course_id">
                                            @foreach(\App\Course::latest()->get() as $item)

                                                <option value="{{ $item->id }}" @if($episode->id == $item->id) checked="checked" @endif>{{ $item->title }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="title">وضعیت ویدئو</label>
                                        <select id="type" name="type" class="form-control">
                                            <option value="vip" @if($episode->type=='vip') selected @endif>اعضای ویژه</option>
                                            <option value="free"  @if($episode->type=='free') selected @endif>رایگان</option>
                                            <option value="cach" @if($episode->type=='cach') selected @endif>نقدی</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="description">متن</label>
                                    <textarea rows="5" class="form-control" placeholder="متن" name="description" id="description">{{$episode->description}}</textarea>
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-sm-6">
                                        <label for="videoUrl">لینک ویدئو</label>
                                        <input class="form-control" placeholder="لینک ویدئو" name="videoUrl" id="videoUrl" value="{{$episode->videoUrl}}">
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="number">شماره ویدئو</label>
                                        <input class="form-control" placeholder="شماره ویدئو" name="number" id="number" value="{{$episode->number}}">
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-sm-6">
                                        <label for="tags">برچسب ها</label>
                                        <input type="text" class="form-control" placeholder="برچسب ها" name="tags" id="tags" value="{{$episode->tags}}">
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="time">زمان ویدئو</label>
                                        <input type="text" class="form-control" placeholder="زمان" name="time" id="time" value="{{$episode->time}}">
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <input type="submit" value="ویرایش ویدئو" class="btn btn-success">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@section('footer')
    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        window.onload = function() {
            CKEDITOR.replace( 'description', {
                filebrowserUploadUrl: '{{ route('upload',['_token' => csrf_token() ]) }}'
            });
        };
        $(document).ready(function(){
            $('#course_id').selectpicker({
                noneSelectedText : 'لطفا دوره ی مورد نظر را انتخاب کنید'
            });
        });
    </script>
@endsection

resources/views/Admin/Episodes/index.blade.php
@extends('Admin.master')

@section('content')

    <div class="panel panel-headline">
        <div class="panel-heading">
            <h3 class="panel-title">ویدئوها</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <!-- BORDERED TABLE -->
                    <div class="panel">
                        <div class="panel-heading">
                            <a href="{{route('episodes.create')}}"  class="btn btn-primary"> ویدئو جدید</a>
                        </div>
                        <div class="panel-body">
                            <table class="table table-bordered">
                                <thead>
                                <tr>

                                    <th>عنوان ویدئو</th>
                                    <th>تعداد نظرات</th>
                                    <th>مقدار بازدید</th>
                                    <th>تعداد دانلود</th>
                                    <th>وضعیت ویدئو</th>
                                    <th>تنظیمات</th>

                                </tr>
                                </thead>
                                <tbody>
                                    @foreach($episodes as $episode)
                                        <tr>
                                            <td><a href="{{$episode->path()}}">{{$episode->title}}</a> </td>
                                            <td>{{$episode->commentCount}}</td>
                                            <td>{{$episode->viewCount}}</td>
                                            <td>{{ $episode->downloadCount }}</td>
                                            <td>
                                                @if($episode->type=='free')
                                                    رایگان
                                                @elseif($episode->type=='vip')
                                                    اعضای ویژه
                                                @else
                                                نقدی
                                                @endif
                                            </td>
                                            <td>
                                                <form action="{{ route('episodes.destroy' , ['id' => $episode->id]) }}" method="post">
                                                    {{method_field('delete')}}
                                                    {{csrf_field()}}
                                                    <div class="btn-group btn-group-lg">
                                                        <a href="{{route('episodes.edit',['id' => $episode->id])}}"  class="btn-sm btn-primary">ویرایش</a>
                                                        <button type="submit" class="btn-sm btn-danger">حذف</button>
                                                    </div>

                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div style="text-align: center">
                            {{ $episodes->render() }}
                        </div>
                    </div>
                    <!-- END BORDERED TABLE -->
                </div>
            </div>
        </div>
    </div>


@endsection